flyway.locations=filesystem:/flyway/sql/versioned,filesystem:/flyway/sql/repeatable,filesystem:/flyway/sql/callbacks
flyway.sqlMigrationPrefix=V
flyway.repeatableSqlMigrationPrefix=R
flyway.sqlMigrationSeparator=__
flyway.sqlMigrationSuffixes=.sql
flyway.validateOnMigrate=true
flyway.cleanDisabled=true
